# https://github.com/mikepenz/FastAdapter/blob/develop/.github/workflows/ci.yml
# https://github.com/coil-kt/coil/blob/master/.github/workflows/ci.yml
name: Android CI

on:
  push:
    #branches: [ master ]
    #tags:
    #  - '*'
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        
    - name: Validate gradle wrapper
      uses: gradle/wrapper-validation-action@v1
        
    - name: Copy CI gradle.properties
      run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties
      
    - name: Checkout Gradle Build Cache
      if: ${{ steps.self_hosted.outputs.FLAG != 'self-hosted' }}
      uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
          !~/.gradle/wrapper/dists/**/gradle*.zip
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/buildSrc/src/main/kotlin/*', '**/gradle/wrapper/gradle-wrapper.properties') }}
        restore-keys: |
          gradle-${{ runner.os }}-
        
    - name: Build
      run: ./gradlew clean app:assembleDebug
      
    - name: Unit tests
      run: ./gradlew test
      
  lint:
    name: Lint
    runs-on: ubuntu-latest
        
    steps:
    - uses: actions/checkout@v2
    
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    
    - name: Check style
      #if: github.event_name  == 'pull_request'
      run: ./gradlew lintKotlin
